---
servername: "URL"
documentroot: "/var/www/html/"

apache_enablerepo: ""

apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443

apache_create_vhosts: true
apache_vhosts_filename: "host.conf"
apache_vhosts_template: "vhosts.conf.j2"
apache_vhosts_template_ssl: "full.conf.j2"
