---
- name: restart docker
  service:
    name: docker
    state: "{{ docker_restart_handler_state }}"
  become: yes

- name: enable
  systemd:
    name: docker.service
    enabled: yes
  become: yes

- name: start
  systemd:
    name: docker.service
    state: start
  become: yes
