---
#- name: Configure Apache.
#  lineinfile:
#    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
#    regexp: "{{ item.regexp }}"
#    line: "{{ item.line }}"
#    state: present
#  with_items: "{{ apache_ports_configuration_items }}"
#  notify: restart apache

#- name: Check whether certificates defined in vhosts exist.
#  stat: path={{ item.certificate_file }}
#  register: apache_ssl_certificates
#  with_items: "{{ apache_vhosts_ssl }}"

- name: Add apache hosts configuracao.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/conf.d/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart apache
#  when: apache_create_vhosts

#- name: Add apache hosts configuracao.
#  template:
#    src: "{{ apache_vhosts_template_ssl }}"
#    dest: "{{ apache_conf_path }}/conf.d/{{ apache_vhosts_filename }}"
#    owner: root
#    group: root
#    mode: 0644
#  become: yes
#  notify: restart apache
