---
- name: restart apache
  service:
    name: "{{ apache_service }}"
    state: restarted
  become: yes

- name: apache stopped
  service:
    name: "{{ apache_service }}"
    state: stopped
  become: yes

- name: apache started
  service:
    name: "{{ apache_service }}"
    state: started
  become: yes
