---
- name: install apt-transport-https
  apt:
    name:
      - apt-transport-https
      - curl
    state: latest
  become: yes

- name: Upgrade
  apt:
    name: "*"
    state: latest
    force_apt_get: True
    update_cache: yes
  become: yes

#- name: Ensure old versions of Docker are not installed.
#  package:
#    name:
#      - docker
#      - docker-engine
#    state: absent

#- name: Ensure dependencies are installed.
#  apt:
#    name:
#      - apt-transport-https
#      - ca-certificates
#    state: present
#    become: yes

#- name: Add Docker apt key.
#  apt_key:
#    url: https://download.docker.com/linux/ubuntu/gpg
#    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
#    state: present
#  register: add_repository_key
#  ignore_errors: "{{ docker_apt_ignore_key_error }}"

#- name: Ensure curl is present (on older systems without SNI).
#  package: name=curl state=present
#  when: add_repository_key is failed

- name: Install Docker
  shell: "sudo curl -fsSl https://get.docker.com/ | sh"
  become: yes


#- name: Add Docker repository.
#  apt_repository:
#    repo: "{{ docker_apt_repository }}"
#    state: present
#    update_cache: true
#  become: yes
